language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ed3QaDEP/spX6ebeSjlZfLZ/s8uTgBAmgBcd4cIRVZ84DBsp6v8O98ieqjOIzwlp4VPt68erANRtTQVKwVgHd6dBZ71l2ohZvF5CWW6yCqFAoblOZh460GhJFjbHTG3ok3TUwyGleyCQ56HbnpoEmRXOWV5ep1/yX57+kFQQopN6qKk8fZKFPRWUReloesFKT9mghtAsRbF1k4m7ZbJjhXOh7+AOOlPzBShNFbOK36d/VoPZMNyRF4MvSg88WP/DdW3VULc2IKKQ11AS0brOk6NoqMndzIqdOi0MF5xwJJ3P239YPvXmi7akzNXPKj9szdfu7OlSrqAmDRArxmyCvRUlR0kw0FGO3Uw5rKDZfricnXxDUmCecM+a5SoLAavYDWszI+te4pWux4rsFSDisjg2RaITVTDUH2aNEGABKvaYr7KCvQhZ+BENZW/IWiQQHumHiQbdbDhZTQJ7wydA85av2g52VEmWbLo894GwfpW00D4jrErSOaEXEP6TI7/sTzxgVUhCJgJMa4uHV2nz+opWK/NnXuZVn/b8SqkNnf1yRUk08GwTNyX1UejqTWuJA2ThV5uEgovMMAihvE4hEQm5YfAuhu+kX2JhnZVxpHtr7W/IFBNuLTwVyWoLoUZcv3ux+Uo6jW1zf202WnLl2y/owQaA9MT2aZ+oqDMmAxA=
  app: secret-depths-15744
  on:
    repo: eshirazp/blog_api
